SuperLibrary.Web/Controllers/BooksController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SuperLibrary.Web.Data;
using SuperLibrary.Web.Helper;
using SuperLibrary.Web.Models;

namespace SuperLibrary.Web.Controllers;

public class BooksController : Controller
{
    private readonly IBookRepository _bookRepository;
    private readonly IUserHelper _userHelper;
    private readonly IBlobHelper _blobHelper;
    private readonly IConverterHelper _converterHelper;

    public BooksController(
        IBookRepository bookRepository,
        IUserHelper userHelper,
        IBlobHelper blobHelper,
        IConverterHelper converterHelper)
    {
        _bookRepository = bookRepository;
        _userHelper = userHelper;
        _blobHelper = blobHelper;
        _converterHelper = converterHelper;
    }

    /// <summary>
    /// Displays a list of all books in the library, ordered by title.
    /// </summary>
    /// <returns></returns>
    public IActionResult Index()
    {
        return View(_bookRepository.GetAll().OrderBy(b => b.Title));
    }

    /// <summary>
    /// Displays the details of a specific book based on its ID.
    /// </summary>
    /// <param name="id"></param>
    /// <returns></returns>
    public async Task<IActionResult> Details(int? id)
    {
        if (id == null)
        {
            return new NotFoundViewResult("BookNotFound");
        }

        var book = await _bookRepository.GetByIdAsync(id.Value);
        if (book == null)
        {
            return new NotFoundViewResult("BookNotFound");
        }

        return View(book); 
    }

    /// <summary>
    /// Displays the view for creating a new book entry.
    /// </summary>
    /// <returns></returns>
    [Authorize(Roles = "Admin,Employee")]
    public IActionResult Create()
    {
        return View();
    }

    /// <summary>
    /// Handles the submission of a new book entry.
    /// </summary>
    /// <param name="model"></param>
    /// <returns></returns>
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(BookViewModel model)
    {
        if (ModelState.IsValid)
        {
            Guid imageId = Guid.Empty;

            if (model.ImageFile != null && model.ImageFile.Length > 0)
            {
                imageId = await _blobHelper.UploadBlobAsync(model.ImageFile, "books");
            }

            var book = _converterHelper.ToBook(model, imageId, true);

            book.User = await _userHelper.GetUserByNameAsync(this.User.Identity.Name);
            await _bookRepository.CreateAsync(book);
            return RedirectToAction(nameof(Index));
        }
        return View(model);
    }

    /// <summary>
    /// Displays the view for editing an existing book entry based on its ID.
    /// </summary>
    /// <param name="id"></param>
    /// <returns></returns>
    [Authorize(Roles = "Admin,Employee")]
    public async Task<IActionResult> Edit(int? id)
    {
        if (id == null)
        {
            return new NotFoundViewResult("BookNotFound");
        }

        var book = await _bookRepository.GetByIdAsync(id.Value);
        if (book == null)
        {
            return new NotFoundViewResult("BookNotFound");
        }

        var model = _converterHelper.ToBookViewModel(book);
        return View(model);
    }

    /// <summary>
    /// Handles the submission of the edited book details.
    /// </summary>
    /// <param name="model"></param>
    /// <returns></returns>
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(BookViewModel model)
    {
        if (ModelState.IsValid)
        {
            try
            {
                Guid imageId = model.ImageId;

                if (model.ImageFile != null && model.ImageFile.Length > 0)
                {
                    imageId = await _blobHelper.UploadBlobAsync(model.ImageFile, "books");
                }

                var book = _converterHelper.ToBook(model, imageId, false);

                book.User = await _userHelper.GetUserByNameAsync(this.User.Identity.Name);
                await _bookRepository.UpdateAsync(book);
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!await _bookRepository.ExistAsync(model.Id))
                {
                    return new NotFoundViewResult("BookNotFound");
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
        }
        return View(model);
    }

    /// <summary>
    /// Displays the confirmation view for deleting a book based on its ID.
    /// </summary>
    /// <param name="id"></param>
    /// <returns></returns>
    [Authorize(Roles = "Admin,Employee")]
    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null)
        {
            return new NotFoundViewResult("BookNotFound");
        }

        var book = await _bookRepository.GetByIdAsync(id.Value);
        if (book == null)
        {
            return new NotFoundViewResult("BookNotFound");
        }

        return View(book);
    }

    /// <summary>
    /// Handles the deletion of a book entry based on its ID.
    /// </summary>
    /// <param name="id"></param>
    /// <returns></returns>
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        var book = await _bookRepository.GetByIdAsync(id);
        
        try
        {
            await _bookRepository.DeleteAsync(book);
            return RedirectToAction(nameof(Index));
        }
        catch (DbUpdateException ex)
        {
            if (ex.InnerException != null && ex.InnerException.Message.Contains("DELETE"))
            {
                ViewBag.ErrorTitle = $"Book {book.Title} is beiong used...</br>";
                ViewBag.ErrorMessage = $"Book {book.Title} can't be deleted due to existing loans/reservations</br></br>" +
                    $"Please delete all associated Loans and Reservations to Delete the current book."; 
            }

            return View("Error");
        }
    }

    /// <summary>
    /// Displays a view when a book is not found, typically for 404 errors.
    /// </summary>
    /// <returns></returns>
    public IActionResult BookNotFound()
    {
        return View();
    }


}

SuperLibrary.Web/Controllers/LoansController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SuperLibrary.Web.Data;
using SuperLibrary.Web.Models;

namespace SuperLibrary.Web.Controllers;

[Authorize]
public class LoansController : Controller
{
    private readonly ILoanRepository _loanRepository;
    private readonly IBookRepository _bookRepository;

    public LoansController(ILoanRepository loanRepository, IBookRepository bookRepository)
    {
        _loanRepository = loanRepository;
        _bookRepository = bookRepository;
    }

    /// <summary>
    /// Displays the index view for loans, showing the current user's loan details.
    /// </summary>
    /// <returns></returns>
    public async Task<IActionResult> Index()
    {
        var model = await _loanRepository.GetLoanAsync(this.User.Identity.Name);
        return View(model);
    }

    /// <summary>
    /// Displays the view for creating a new loan, showing temporary loan details for the current user.
    /// </summary>
    /// <returns></returns>
    public async Task<IActionResult> Create()
    {
        var model = await _loanRepository.GetDetailTempsAsync(this.User.Identity.Name);
        return View(model);
    }

    /// <summary>
    /// Displays the view for adding a new book to the loan.
    /// </summary>
    /// <returns></returns>
    public IActionResult AddBook()
    {
        var model = new AddItemViewModel
        {
            Quantity = 1,
            Books = _bookRepository.GetComboBooks()
        };

        return View(model);
    }

    /// <summary>
    /// Handles the addition of a new book to the loan based on the provided model.
    /// </summary>
    /// <param name="model"></param>
    /// <returns></returns>
    [HttpPost]
    public async Task<IActionResult> AddBook(AddItemViewModel model)
    {
        if (ModelState.IsValid)
        {
            await _loanRepository.AddItemToLoanAsync(model, this.User.Identity.Name);
            return RedirectToAction("Create");
        }

        return View(model);
    }

    /// <summary>
    /// Deletes a specific item from the temporary loan details based on the provided ID.
    /// </summary>
    /// <param name="id"></param>
    /// <returns></returns>
    public async Task<IActionResult> DeleteItem(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        await _loanRepository.DeleteLoanDetailTempAsync(id.Value);
        return RedirectToAction("Create");
    }

    /// <summary>
    /// Increases the quantity of a specific item in the temporary loan details by 1 based on the provided ID.
    /// </summary>
    /// <param name="id"></param>
    /// <returns></returns>
    public async Task<IActionResult> Increase(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        await _loanRepository.ModifyLoanDetailTempQuantityAsync(id.Value, 1);
        return RedirectToAction("Create");
    }

    /// <summary>
    /// Decreases the quantity of a specific item in the temporary loan details by 1 based on the provided ID.
    /// </summary>
    /// <param name="id"></param>
    /// <returns></returns>
    public async Task<IActionResult> Decrease(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        await _loanRepository.ModifyLoanDetailTempQuantityAsync(id.Value, -1);
        return RedirectToAction("Create");
    }

    /// <summary>
    /// Confirms the loan for the current user, finalizing the loan process and redirecting to the index view.
    /// </summary>
    /// <returns></returns>
    public async Task<IActionResult> ConfirmLoan()
    {
        var response = await _loanRepository.ConfirmLoanAsync(this.User.Identity.Name);
        if (response)
        {
            return RedirectToAction("Index");
        }

        return RedirectToAction("Create");
    }

    /// <summary>
    /// Displays the view for delivering a loan based on the provided ID, initializing the delivery date to today.
    /// </summary>
    /// <param name="id"></param>
    /// <returns></returns>
    public async Task<IActionResult> Deliver(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var loan = await _loanRepository.GetLoanAsync(id.Value);
        if (loan == null || loan.WasDeleted)
        {
            return NotFound();
        }

        var model = new DeliveryViewModel
        {
            Id = loan.Id,
            DeliveryDate = DateTime.Today,
        };

        return View(model); 
    }

    /// <summary>
    /// Handles the delivery of a loan based on the provided model, updating the delivery date and redirecting to the index view.
    /// </summary>
    /// <param name="model"></param>
    /// <returns></returns>
    [HttpPost]
    public async Task<IActionResult> Deliver(DeliveryViewModel model)
    {
        if (ModelState.IsValid)
        {
            await _loanRepository.DeliverLoan(model);
            return RedirectToAction("Index");
        }

       return View();
    }
}

SuperLibrary.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Super Library</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap-datepicker/css/bootstrap-datepicker.min.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><i class="fa-solid fa-book-atlas fa-xl" style="color: #74C0FC;"> Super Library</i></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Books" asp-action="Index"><i class="fa-brands fa-sistrix"></i> Search</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Books" asp-action="Index"><i class="fa-solid fa-book"></i> Books</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Loans" asp-action="Index"><i class="fa-solid fa-handshake"></i> Loans</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" href="http://SuperLibraryApi.somee.com" target="_blank"><i class="fa-solid fa-newspaper"></i> Api</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy"><i class="fa-solid fa-circle-info"></i> Privacy</a>
                        </li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        @if (this.User.Identity.IsAuthenticated && this.User.IsInRole("Admin"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa-solid fa-users-gear"></i> Manage</a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Account" asp-action="ManageUsers"><i class="fa-solid fa-users"></i> Users</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Account" asp-action="EmployeeList"><i class="fa-solid fa-user-tie"></i> Roles</a></li>
                                </ul>
                            </li>
                        }
                        @if (this.User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa-solid fa-user"></i> @this.User.Identity.Name</a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Account" asp-action="AddUser"><i class="fa-solid fa-user-plus"></i> Add User</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Account" asp-action="ChangeUser"><i class="fa-solid fa-user-pen"></i> Edit Profile</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Account" asp-action="Profile"><i class="fa-solid fa-user-pen"></i> Profile</a></li>
                                </ul>
                            </li>
                            <li>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout"><i class="fa-solid fa-arrow-right-from-bracket"></i> Logout</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login"><i class="fa-solid fa-arrow-right-to-bracket"></i> Login</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.ToString("yyyy") - Super Library - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/bootstrap-datepicker/js/bootstrap-datepicker.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>